/**
 * Mock / demo data used as fallbacks when the backend API is unavailable.
 * All data is realistic but fictional – for demonstration only.
 */

export const MOCK_STATS = {
  active_projects: 847,
  pending_clearances: 1423,
  avg_days_to_issue: 34,
  bottlenecks_detected: 18,
};

export const MOCK_BOTTLENECKS = [
  {
    id: "bn-001",
    address: "14823 Sunset Blvd, Pacific Palisades, CA 90272",
    project_address: "14823 Sunset Blvd, Pacific Palisades, CA 90272",
    department: "Planning",
    clearance_type: "Coastal Zone Review",
    days_stuck: 47,
    predicted_days: 55,
    is_bottleneck: true,
  },
  {
    id: "bn-002",
    address: "2104 Altadena Dr, Altadena, CA 91001",
    project_address: "2104 Altadena Dr, Altadena, CA 91001",
    department: "Fire",
    clearance_type: "Fire Hazard Clearance",
    days_stuck: 38,
    predicted_days: 45,
    is_bottleneck: true,
  },
  {
    id: "bn-003",
    address: "756 Castellammare Dr, Pacific Palisades, CA 90272",
    project_address: "756 Castellammare Dr, Pacific Palisades, CA 90272",
    department: "LADBS",
    clearance_type: "Structural Plan Check",
    days_stuck: 31,
    predicted_days: 40,
    is_bottleneck: true,
  },
  {
    id: "bn-004",
    address: "4490 Via Marisol, Altadena, CA 91001",
    project_address: "4490 Via Marisol, Altadena, CA 91001",
    department: "DWP",
    clearance_type: "Utility Service Check",
    days_stuck: 29,
    predicted_days: 35,
    is_bottleneck: true,
  },
  {
    id: "bn-005",
    address: "1833 Marquez Ave, Pacific Palisades, CA 90272",
    project_address: "1833 Marquez Ave, Pacific Palisades, CA 90272",
    department: "Planning",
    clearance_type: "Historic Review",
    days_stuck: 22,
    predicted_days: 28,
    is_bottleneck: true,
  },
];

export const MOCK_PROJECTS = {
  items: [
    {
      id: "proj-001",
      address: "14823 Sunset Blvd, Pacific Palisades, CA 90272",
      pathway: "eo1",
      status: "in_review",
      predicted_days: 42,
      is_coastal: true,
      is_hillside: false,
      created_at: "2026-01-15T08:00:00Z",
    },
    {
      id: "proj-002",
      address: "2104 Altadena Dr, Altadena, CA 91001",
      pathway: "standard",
      status: "approved",
      predicted_days: 55,
      is_coastal: false,
      is_hillside: true,
      created_at: "2026-01-20T09:30:00Z",
    },
    {
      id: "proj-003",
      address: "756 Castellammare Dr, Pacific Palisades, CA 90272",
      pathway: "coastal",
      status: "not_started",
      predicted_days: 68,
      is_coastal: true,
      is_hillside: true,
      created_at: "2026-01-22T14:00:00Z",
    },
    {
      id: "proj-004",
      address: "4490 Via Marisol, Altadena, CA 91001",
      pathway: "eo8",
      status: "conditional",
      predicted_days: 35,
      is_coastal: false,
      is_hillside: false,
      created_at: "2026-02-01T10:00:00Z",
    },
    {
      id: "proj-005",
      address: "1833 Marquez Ave, Pacific Palisades, CA 90272",
      pathway: "hillside",
      status: "in_review",
      predicted_days: 78,
      is_coastal: false,
      is_hillside: true,
      created_at: "2026-02-05T11:00:00Z",
    },
    {
      id: "proj-006",
      address: "3217 Fernwood Ave, Altadena, CA 91001",
      pathway: "standard",
      status: "approved",
      predicted_days: 30,
      is_coastal: false,
      is_hillside: false,
      created_at: "2026-02-08T09:00:00Z",
    },
    {
      id: "proj-007",
      address: "920 Chautauqua Blvd, Pacific Palisades, CA 90272",
      pathway: "eo1",
      status: "denied",
      predicted_days: null,
      is_coastal: true,
      is_hillside: false,
      created_at: "2026-02-10T13:00:00Z",
    },
    {
      id: "proj-008",
      address: "1654 Loma Linda Dr, Altadena, CA 91001",
      pathway: "standard",
      status: "not_started",
      predicted_days: 50,
      is_coastal: false,
      is_hillside: false,
      created_at: "2026-02-15T16:00:00Z",
    },
  ],
  total: 847,
  page: 1,
  size: 20,
  pages: 43,
};

export const MOCK_KANBAN = {
  not_started: [
    {
      id: "cl-001",
      address: "756 Castellammare Dr, Pacific Palisades, CA",
      project_address: "756 Castellammare Dr, Pacific Palisades, CA",
      department: "Planning",
      clearance_type: "Coastal Zone Review",
      predicted_days: 68,
      is_bottleneck: false,
      status: "not_started",
    },
    {
      id: "cl-002",
      address: "1654 Loma Linda Dr, Altadena, CA",
      project_address: "1654 Loma Linda Dr, Altadena, CA",
      department: "LADBS",
      clearance_type: "Structural Plan Check",
      predicted_days: 50,
      is_bottleneck: false,
      status: "not_started",
    },
    {
      id: "cl-003",
      address: "4821 Arden Rd, Altadena, CA",
      project_address: "4821 Arden Rd, Altadena, CA",
      department: "DWP",
      clearance_type: "Utility Service Check",
      predicted_days: 25,
      is_bottleneck: false,
      status: "not_started",
    },
  ],
  in_review: [
    {
      id: "cl-004",
      address: "14823 Sunset Blvd, Pacific Palisades, CA",
      project_address: "14823 Sunset Blvd, Pacific Palisades, CA",
      department: "Planning",
      clearance_type: "Coastal Zone Review",
      predicted_days: 42,
      is_bottleneck: true,
      status: "in_review",
    },
    {
      id: "cl-005",
      address: "1833 Marquez Ave, Pacific Palisades, CA",
      project_address: "1833 Marquez Ave, Pacific Palisades, CA",
      department: "Planning",
      clearance_type: "Historic Review",
      predicted_days: 28,
      is_bottleneck: true,
      status: "in_review",
    },
    {
      id: "cl-006",
      address: "2104 Altadena Dr, Altadena, CA",
      project_address: "2104 Altadena Dr, Altadena, CA",
      department: "Fire",
      clearance_type: "Fire Hazard Clearance",
      predicted_days: 45,
      is_bottleneck: false,
      status: "in_review",
    },
    {
      id: "cl-007",
      address: "3217 Fernwood Ave, Altadena, CA",
      project_address: "3217 Fernwood Ave, Altadena, CA",
      department: "LADBS",
      clearance_type: "Grading Review",
      predicted_days: 30,
      is_bottleneck: false,
      status: "in_review",
    },
  ],
  approved: [
    {
      id: "cl-008",
      address: "3217 Fernwood Ave, Altadena, CA",
      project_address: "3217 Fernwood Ave, Altadena, CA",
      department: "LAFD",
      clearance_type: "Fire Safety Clearance",
      predicted_days: 14,
      is_bottleneck: false,
      status: "approved",
    },
    {
      id: "cl-009",
      address: "4490 Via Marisol, Altadena, CA",
      project_address: "4490 Via Marisol, Altadena, CA",
      department: "Health",
      clearance_type: "Environmental Health",
      predicted_days: 20,
      is_bottleneck: false,
      status: "approved",
    },
    {
      id: "cl-010",
      address: "920 Chautauqua Blvd, Pacific Palisades, CA",
      project_address: "920 Chautauqua Blvd, Pacific Palisades, CA",
      department: "LADBS",
      clearance_type: "Electrical Plan Check",
      predicted_days: 18,
      is_bottleneck: false,
      status: "approved",
    },
  ],
  conditional: [
    {
      id: "cl-011",
      address: "4490 Via Marisol, Altadena, CA",
      project_address: "4490 Via Marisol, Altadena, CA",
      department: "Planning",
      clearance_type: "EO8 Pathway Approval",
      predicted_days: 35,
      is_bottleneck: false,
      status: "conditional",
    },
    {
      id: "cl-012",
      address: "8204 Saddle Peak Rd, Malibu, CA",
      project_address: "8204 Saddle Peak Rd, Malibu, CA",
      department: "Coastal Commission",
      clearance_type: "Coastal Development Permit",
      predicted_days: 90,
      is_bottleneck: true,
      status: "conditional",
    },
  ],
  denied: [
    {
      id: "cl-013",
      address: "920 Chautauqua Blvd, Pacific Palisades, CA",
      project_address: "920 Chautauqua Blvd, Pacific Palisades, CA",
      department: "Planning",
      clearance_type: "Height Exception",
      predicted_days: null,
      is_bottleneck: false,
      status: "denied",
    },
  ],
};

export const MOCK_PIPELINE = {
  departments: [
    { department: "Planning", total: 312, completed: 245, completion_rate: 79, avg_processing_days: 28, bottleneck_count: 6 },
    { department: "LADBS", total: 421, completed: 389, completion_rate: 92, avg_processing_days: 14, bottleneck_count: 2 },
    { department: "Fire", total: 198, completed: 156, completion_rate: 79, avg_processing_days: 21, bottleneck_count: 4 },
    { department: "DWP", total: 276, completed: 198, completion_rate: 72, avg_processing_days: 35, bottleneck_count: 7 },
    { department: "Health", total: 134, completed: 128, completion_rate: 96, avg_processing_days: 8, bottleneck_count: 1 },
    { department: "Coastal", total: 87, completed: 42, completion_rate: 48, avg_processing_days: 62, bottleneck_count: 9 },
    { department: "Soils", total: 156, completed: 134, completion_rate: 86, avg_processing_days: 18, bottleneck_count: 3 },
  ],
  summary: {
    total_clearances: 1584,
    total_completed: 1292,
    overall_completion_rate: 82,
    total_bottlenecks: 18,
  },
};

export const MOCK_TREND_DATA = {
  permits_issued: [
    { date: "2026-03-24", value: 12 },
    { date: "2026-03-25", value: 18 },
    { date: "2026-03-26", value: 9 },
    { date: "2026-03-27", value: 22 },
    { date: "2026-03-28", value: 27 },
    { date: "2026-03-29", value: 15 },
    { date: "2026-03-30", value: 20 },
  ],
  clearances_completed: [
    { date: "2026-03-24", value: 34 },
    { date: "2026-03-25", value: 41 },
    { date: "2026-03-26", value: 28 },
    { date: "2026-03-27", value: 52 },
    { date: "2026-03-28", value: 48 },
    { date: "2026-03-29", value: 39 },
    { date: "2026-03-30", value: 45 },
  ],
  bottlenecks_detected: [
    { date: "2026-03-24", value: 22 },
    { date: "2026-03-25", value: 20 },
    { date: "2026-03-26", value: 21 },
    { date: "2026-03-27", value: 19 },
    { date: "2026-03-28", value: 18 },
    { date: "2026-03-29", value: 17 },
    { date: "2026-03-30", value: 18 },
  ],
};

export const MOCK_EQUITY_DATA = {
  areas: [
    { area: "Pacific Palisades", project_count: 423, avg_predicted_days: 38, avg_actual_days: 41 },
    { area: "Altadena", project_count: 312, avg_predicted_days: 32, avg_actual_days: 35 },
    { area: "Malibu Coastal", project_count: 67, avg_predicted_days: 72, avg_actual_days: 89 },
    { area: "Topanga", project_count: 45, avg_predicted_days: 45, avg_actual_days: 48 },
  ],
  languages: [
    { language: "en", count: 612 },
    { language: "es", count: 178 },
    { language: "zh", count: 34 },
    { language: "ko", count: 23 },
  ],
  pathways: [
    { pathway: "standard", count: 389, avg_predicted_days: 45 },
    { pathway: "eo1", count: 213, avg_predicted_days: 28 },
    { pathway: "eo8", count: 156, avg_predicted_days: 32 },
    { pathway: "coastal", count: 67, avg_predicted_days: 78 },
    { pathway: "hillside", count: 22, avg_predicted_days: 55 },
  ],
};

export const MOCK_HEALTH = {
  status: "healthy",
  database: { status: "connected", detail: "PostgreSQL 15.4 — 2.1ms latency" },
  redis: { status: "connected", used_memory_human: "48.2 MB", detail: "48.2 MB used" },
  queue_depth: 12,
  active_projects: 847,
};

export const MOCK_INSPECTIONS_STATS = {
  total_scheduled: 234,
  pass_rate: 78,
  avg_days_between: 18,
  most_common_failure: "Framing",
};

export const MOCK_INSPECTIONS = [
  {
    id: "insp-001",
    project_id: "proj-001",
    address: "14823 Sunset Blvd, Pacific Palisades, CA",
    inspection_type: "Foundation",
    status: "scheduled",
    scheduled_date: "2026-04-02T10:00:00Z",
    completed_date: null,
    inspector_name: "M. Rodriguez",
    failure_reasons: [],
    notes: "Pre-pour concrete inspection",
  },
  {
    id: "insp-002",
    project_id: "proj-002",
    address: "2104 Altadena Dr, Altadena, CA",
    inspection_type: "Framing",
    status: "completed_pass",
    scheduled_date: "2026-03-20T09:00:00Z",
    completed_date: "2026-03-20T11:30:00Z",
    inspector_name: "J. Chen",
    failure_reasons: [],
    notes: null,
  },
  {
    id: "insp-003",
    project_id: "proj-003",
    address: "756 Castellammare Dr, Pacific Palisades, CA",
    inspection_type: "Rough Electrical",
    status: "completed_fail",
    scheduled_date: "2026-03-18T14:00:00Z",
    completed_date: "2026-03-18T15:45:00Z",
    inspector_name: "T. Kim",
    failure_reasons: ["Improper grounding", "Missing junction box cover"],
    notes: "Re-inspection required",
  },
  {
    id: "insp-004",
    project_id: "proj-004",
    address: "4490 Via Marisol, Altadena, CA",
    inspection_type: "Rough Plumbing",
    status: "scheduled",
    scheduled_date: "2026-04-05T08:00:00Z",
    completed_date: null,
    inspector_name: "A. Patel",
    failure_reasons: [],
    notes: null,
  },
  {
    id: "insp-005",
    project_id: "proj-005",
    address: "1833 Marquez Ave, Pacific Palisades, CA",
    inspection_type: "Foundation",
    status: "completed_pass",
    scheduled_date: "2026-03-25T10:00:00Z",
    completed_date: "2026-03-25T12:00:00Z",
    inspector_name: "M. Rodriguez",
    failure_reasons: [],
    notes: null,
  },
  {
    id: "insp-006",
    project_id: "proj-006",
    address: "3217 Fernwood Ave, Altadena, CA",
    inspection_type: "Final Building",
    status: "scheduled",
    scheduled_date: "2026-04-10T09:00:00Z",
    completed_date: null,
    inspector_name: "J. Chen",
    failure_reasons: [],
    notes: "Final sign-off pending",
  },
];
